
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { SITE_NAME } from "@/constants/seo.constants";
import { Providers } from "./prodivers";
import DashboardLayout from '../components/dashboard-layout/DashboardLayout';

const imb = Nunito({ 
  subsets: ["cyrillic", "latin"],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-zen',
  style: 'normal' 
});

export const metadata: Metadata = {
  title: {
    default:SITE_NAME,
    template: `%s | ${SITE_NAME}`
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={imb.className}>
        <Providers>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </Providers>
      </body>
    </html>
  );
}
